"""empty message

Revision ID: 7786d01dee5f
Revises: 
Create Date: 2025-07-06 11:28:38.574367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7786d01dee5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digimons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('REPTIL', 'AVE', 'INSECTO', 'PLANTA', 'BESTIA', 'MAMIFERO', 'DRAGON', name='tipo'), nullable=False),
    sa.Column('atributo', sa.Enum('VACUNA', 'VIRUS', 'INFORMACION', name='atributo'), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('niños',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_niño', sa.Integer(), nullable=True),
    sa.Column('id_digimon', sa.Integer(), nullable=True),
    sa.Column('id_objeto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_digimon'], ['digimons.id'], ),
    sa.ForeignKeyConstraint(['id_niño'], ['niños.id'], ),
    sa.ForeignKeyConstraint(['id_objeto'], ['objetos.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    op.drop_table('users')
    op.drop_table('objetos')
    op.drop_table('niños')
    op.drop_table('digimons')
    # ### end Alembic commands ###
